# -*- coding: utf-8 -*-
"""Python Programing Final

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yqpDv8SAO6CCnuBf0bWTcme6TmS1cSwx

Data Dictionary:

Interval2020 - HOLC Scores (rounded)

HRI2020 - HOLC Scores (weighted average)

1- Grade A - Best

2- Grade B - Desirable

3- Grade C - Declining

4- Grade D - Hazardous

Permit_id - the unique identifier for each permit

Permit_type - the type of permit being used, for this analysis we only focused on Building Permits

Owner_name - the name of the owner for the permit

Work_type - deciption of what type of work is being done in the area, for this analysis we only focused on New Construction

Contractor_name - The entity performing the construction

Work_description - description of the construction being done

Total_Project_Value - the cost cost of the development in USD

Address - Building number and street for each property

Neighborhood - The neighborhood in which the costruction is taking place

PercentWhite_2020 - the percentage of the population in a given tract identifying as white.

avg_income_LI_kids - taken from the Census Bureau Opportunity Atlas, this is the average income of children from a given census tract who grew up with parents with incomes at or below the 25th percentile of the national income distribution.

male_unemployment - the unemployment rate for men between 25 and 64. Curiously, the data we accessed from the Allegheny County Needs Survey did not have the corresponding female unemployment rate.

overdose_rate - the average annual rate of fatal overdoses per 100,000 people, between 2018 and 2022 in this case.

poverty_rate - proportion of families below the poverty line (2022).
"""

!pip install censusgeocode
import censusgeocode as cgc
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import files

permits = "https://raw.githubusercontent.com/RK1141/Python-II-Final-Project-2026/refs/heads/main/f4d1177a-f597-4c32-8cbf-7885f56253f6.csv"
permits_df = pd.read_csv(permits)

redlining = "https://raw.githubusercontent.com/RK1141/Python-II-Final-Project-2026/b346b158318a462ed642f1702a7e88c06922a3f9/Historic%20Redlining%20Indicator%202020.csv"
redlining_df = pd.read_csv(redlining)

needs = "https://raw.githubusercontent.com/RK1141/Python-II-Final-Project-2026/refs/heads/main/Level%20of%20Need%2C%202022%20Five-Year%20Estimates.csv"
needs_df = pd.read_csv(needs)

import time

def get_tract(permit):
  try:
    result = cgc.coordinates(permit["longitude"], permit["latitude"])
    return result["Census Tracts"][0]["GEOID"]
  except Exception:
    time.sleep(0.1)
    return None

new_construction = permits_df[
    permits_df["permit_type"]=="BUILDING"]

new_construction = new_construction[
    new_construction["work_type"].astype(str).str.lower().str.contains("new construction", na=False)
].head(2000)

print(f"Selected {len(new_construction)} new construction permits for further analysis.")
new_construction

new_construction["tract"] = new_construction.apply(get_tract, axis=1)
new_construction.head()

new_construction["tract_clean"] = pd.to_numeric(new_construction["tract"])
redlining_df["GEOID20_clean"] = pd.to_numeric(redlining_df["GEOID20"])

permits_merge = pd.merge(
    new_construction.dropna(subset=["tract_clean"]),
    redlining_df.dropna(subset=["GEOID20_clean"]),
    left_on="tract_clean",
    right_on="GEOID20_clean",
    how="inner")

permits_merge = permits_merge.drop(columns=["commercial_or_residential","METRO_NAME","owner_name","contractor_name","status"])
permits_merge

developments_counts = permits_merge.groupby("INTERVAL2020").size().reset_index(name="number_of_developments")

plt.figure(figsize=(10, 6))
ax = sns.barplot(
    data=developments_counts,
    x="INTERVAL2020",
    y="number_of_developments"
)
plt.title("Amount of Developments Within Each HOLC Score")
plt.ylabel("Number of Developments")
plt.xlabel("HOLC Scores")
ax.bar_label(ax.containers[0])
plt.show()

permits_merge["issue_date"] = pd.to_datetime(permits_merge["issue_date"])
permits_merge["year"] = permits_merge["issue_date"].dt.year

developments_by_year = permits_merge[
    permits_merge["year"].between(2019, 2026)
].groupby(["INTERVAL2020", "year"]).size().reset_index(name="number_of_developments")

for category in developments_by_year["INTERVAL2020"].unique():
    category_data = developments_by_year[developments_by_year["INTERVAL2020"] == category]

    plt.figure(figsize=(8, 5))
    plt.bar(category_data["year"], category_data["number_of_developments"])
    plt.title(f"Number of Developments by Year - HOLC Category {category}")
    plt.xlabel("Year")
    plt.ylabel("Number of Developments")
    plt.xticks(range(2019, 2027))
    plt.show()

mean_values = permits_merge.groupby("INTERVAL2020")["total_project_value"].mean().reset_index()

plt.figure(figsize=(10, 6))

sns.barplot(
    data=mean_values,
    x="INTERVAL2020",
    y="total_project_value",
    order=[1, 2, 3, 4])

plt.title("Mean Development Value by HOLC-Related Category")
plt.xlabel("HOLC-Related Category")
plt.ylabel("Mean Total Project Value ($)")
plt.ticklabel_format(axis="y", style="plain")
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 6))

sns.boxplot(
    data=permits_merge,
    x="INTERVAL2020",
    y="total_project_value",
    boxprops=dict(alpha=0.5)
)

plt.yscale("symlog", linthresh=10000)
plt.title("Individual Construction Project Values by HOLC Score")
plt.xlabel("HOLC Score (INTERVAL2020)")
plt.ylabel("Total Project Value ($)")
plt.tight_layout()
plt.show()

neighborhood_counts = permits_merge["neighborhood"].value_counts()

top_neighborhood = neighborhood_counts.index[0]

holc_score = permits_merge.loc[
    permits_merge["neighborhood"] == top_neighborhood,
    "INTERVAL2020"
].mode()[0]

print("Neighborhood with the most developments:", top_neighborhood)
print("Number of developments:", neighborhood_counts.iloc[0])
print("HOLC score:", holc_score)

needs_merge = pd.merge(needs_df, redlining_df, left_on='GEO_ID_SHORT', right_on='GEOID20', how="left")
needs_merge.dropna(subset = "HRI2020")
needs_pruned = needs_merge[["GEO_ID_SHORT", "INTERVAL2020", "HRI2020", "Avg_Fatal_Overdose_Rate_2018_2022", "PercentWhite_2020", "MaleUnemploymentJoblessnessRate25to64_2022_ACS_5YE", "AvgAdultIncomeOutcomeforLow#incomeKids_OpportunityAtlas", "FamPovRate_2022_ACS_5YE"]]
needs_pruned = needs_merge.rename(columns={'Avg_Fatal_Overdose_Rate_2018_2022': 'overdose_rate', 'MaleUnemploymentJoblessnessRate25to64_2022_ACS_5YE': 'male_unemployment', "AvgAdultIncomeOutcomeforLow#incomeKids_OpportunityAtlas" : "avg_income_LI_kids", "FamPovRate_2022_ACS_5YE" : "poverty_rate"})

sns.barplot(data=needs_pruned, x="INTERVAL2020", y="overdose_rate", errorbar=None)
plt.title("Average Fatal Overdose Rate 2018-2022 by HOLC Category")
plt.xlabel("HOLC Category")
plt.ylabel("Average Annual Fatal Overdose Rate per 100,000")
plt.ticklabel_format(axis="y", style="plain")
plt.tight_layout()
plt.savefig("F_OV_Rate.jpg", format="jpg", dpi=800)
files.download("F_OV_Rate.jpg")
plt.show()

sns.scatterplot(data=needs_pruned, x="HRI2020", y="overdose_rate")
plt.title("Average Annual Fatal Overdose Rate 2018-2022 by HOLC Category")
plt.xlabel("HOLC Category")
plt.ylabel("Fatal Overdose Rate per 100,000")
plt.ticklabel_format(axis="y", style="plain")
plt.tight_layout()
plt.savefig("F_OV_Ratescatter.jpg", format="jpg", dpi=800)
files.download("F_OV_Ratescatter.jpg")
plt.show()

needs_pruned["PercentNonwhite_2020"] = 100-needs_pruned["PercentWhite_2020"]
sns.barplot(data=needs_pruned, x="INTERVAL2020", y="PercentNonwhite_2020", errorbar=None)
plt.title("Average Percentage Non-White Population By HOLC Category")
plt.xlabel("HOLC Category")
plt.ylabel("% Other Than White")
plt.ticklabel_format(axis="y", style="plain")
plt.tight_layout()
plt.savefig("PCT_NWT.jpg", format="jpg", dpi=800)
files.download("PCT_NWT.jpg")
plt.show()

sns.barplot(data=needs_pruned, x="INTERVAL2020", y="avg_income_LI_kids", errorbar=None)
plt.title("Average Adult Income for Low-Income Children")
plt.xlabel("HOLC Category")
plt.ylabel("Average Income")
plt.ticklabel_format(axis="y", style="plain")
plt.tight_layout()
plt.savefig("AVG_A_INCM.jpg", format="jpg", dpi=800)
files.download("AVG_A_INCM.jpg")
plt.show()

sns.barplot(data=needs_pruned, x="INTERVAL2020", y="poverty_rate", errorbar=None)
plt.title("Family Poverty Rate")
plt.xlabel("HOLC Category")
plt.ylabel("Poverty Rate, %")
plt.ticklabel_format(axis="y", style="plain")
plt.tight_layout()
plt.savefig("Fam_pov_Rate.jpg", format="jpg", dpi=800)
files.download("Fam_pov_Rate.jpg")
plt.show()

sns.scatterplot(data=needs_pruned, x="HRI2020", y="poverty_rate")
plt.title("Family Poverty Rate")
plt.xlabel("HOLC Category")
plt.ylabel("Poverty Rate, %")
plt.ticklabel_format(axis="y", style="plain")
plt.tight_layout()
plt.savefig("Fam_pov_Ratescatter.jpg", format="jpg", dpi=800)
files.download("Fam_pov_Ratescatter.jpg")
plt.show()

permits_merge.to_csv('permits_merge', index=False)